### ISSUE TITLE
No module named 'finta'

### ISSUE THREAD

**Issue by XinuxC** [davidzr/freqtrade-strategies#3]
When I was running MacheteV8b with latest freqtrade image, Errror came up:
2024-02-10 13:35:20,739 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/MacheteV8b.py due to 'No module named 'finta''
2024-02-10 13:35:20,739 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'MacheteV8b'. This class does not exist or contains Python code errors.
2024-02-10 13:35:20,739 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
worker = Worker(args)
^^^^^^^^^^^^
File "/freqtrade/freqtrade/worker.py", line 37, in init
self._init(False)
File "/freqtrade/freqtrade/worker.py", line 53, in _init
self.freqtrade = FreqtradeBot(self._config)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/freqtrade/freqtrade/freqtradebot.py", line 71, in init
self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 48, in load_strategy
strategy: IStrategy = StrategyResolver._load_strategy(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 280, in _load_strategy
raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'MacheteV8b'. This class does not exist or contains Python code errors.
root@10-7-126-157:~/freqtrade-v8b# Connection to 101.36.125.70 closed by remote host.
Connection to 101.36.125.70 closed.

How can I fix this?

**Comment by XinuxC** [comment]
solved by build a new image
